apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: basic-node-build
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: basic-node:latest
