apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basic-node.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "basic-node.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "basic-node.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_MESSAGE
              value: {{ .Values.env.APP_MESSAGE | quote }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.pathLiveness }}
              port: 8080
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.pathReadiness }}
              port: 8080
