apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-message
spec:
  params:
    - name: message
      type: string
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi-minimal
      script: |
        #!/usr/bin/env sh
        echo "$(params.message)"
