apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      labels:
        app: switchable
        color: green
    spec:
      volumes:
        - name: shared
          emptyDir: {}
      initContainers:
        - name: init
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/sh", "-c", "echo green > /work/color"]
          volumeMounts:
            - name: shared
              mountPath: /work
      containers:
        - name: app
          image: registry.access.redhat.com/ubi9/nginx-122
          volumeMounts:
            - name: shared
              mountPath: /usr/share/nginx/html
