apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-node
  template:
    metadata:
      labels:
        app: basic-node
    spec:
      containers:
        - name: app
          image: registry.access.redhat.com/ubi9/nodejs-20:latest
          command: ["node", "/opt/app-root/src/server.js"]
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: code-vol
              mountPath: /opt/app-root/src/server.js
              subPath: server.js
            - name: secret-vol
              mountPath: /opt/app-root/src/secret
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
      volumes:
        - name: code-vol
          configMap:
            name: app-code
        - name: secret-vol
          secret:
            secretName: app-secret
