apiVersion: v1
kind: Namespace
metadata:
  name: ex280-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: ex280
---
apiVersion: v1
kind: Namespace
metadata:
  name: ex288-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: ex288
---
apiVersion: v1
kind: Namespace
metadata:
  name: ex370-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: ex370
---
apiVersion: v1
kind: Namespace
metadata:
  name: ex380-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: ex380
---
apiVersion: v1
kind: Namespace
metadata:
  name: ex480-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: ex480
---
apiVersion: v1
kind: Namespace
metadata:
  name: ex482-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: ex482
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox-lab
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
    platform.mayabank.example/purpose: certification-lab
    platform.mayabank.example/track: sandbox
