apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: basic-pipeline
spec:
  params:
    - name: message
      type: string
  tasks:
    - name: say
      taskRef:
        name: echo-message
      params:
        - name: message
          value: "$(params.message)"
