apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-rbac
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: openshift-platform-blueprints
spec:
  project: default
  source:
    repoURL: https://github.com/zdmooc/openshift-platform-blueprints.git
    targetRevision: main
    path: platform/gitops/cluster-config/rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
