apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-platform-namespaces.yaml
  - application-platform-quotas.yaml
  - application-platform-rbac.yaml
  - application-platform-network.yaml
  - application-platform-observability.yaml
  - application-platform-demo-metrics.yaml
