apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: basic-node-dc
spec:
  replicas: 1
  selector:
    app: basic-node-dc
  template:
    metadata:
      labels:
        app: basic-node-dc
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/ex288-lab05/basic-node:latest
          ports:
            - containerPort: 8080
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo started"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "echo stopping"]
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - app
        from:
          kind: ImageStreamTag
          name: basic-node:latest
