apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-node-k
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app
          env:
            - name: APP_MESSAGE
              value: hello from kustomize prod
